// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  CreateDeckApiDecksPostData,
  CreateDeckApiDecksPostErrors,
  CreateDeckApiDecksPostResponses,
  CreateImageJobApiAssetsJobsPostData,
  CreateImageJobApiAssetsJobsPostErrors,
  CreateImageJobApiAssetsJobsPostResponses,
  CreateJobApiGenerationJobsPostData,
  CreateJobApiGenerationJobsPostErrors,
  CreateJobApiGenerationJobsPostResponses,
  DeleteDeckApiDecksDeckIdDeleteData,
  DeleteDeckApiDecksDeckIdDeleteErrors,
  DeleteDeckApiDecksDeckIdDeleteResponses,
  DuplicateDeckApiDecksDeckIdDuplicatePostData,
  DuplicateDeckApiDecksDeckIdDuplicatePostErrors,
  DuplicateDeckApiDecksDeckIdDuplicatePostResponses,
  EditApiAiEditPostData,
  EditApiAiEditPostErrors,
  EditApiAiEditPostResponses,
  ExportHtmlApiDecksDeckIdExportHtmlGetData,
  ExportHtmlApiDecksDeckIdExportHtmlGetErrors,
  ExportHtmlApiDecksDeckIdExportHtmlGetResponses,
  ExportPptxApiDecksDeckIdExportPptxGetData,
  ExportPptxApiDecksDeckIdExportPptxGetErrors,
  ExportPptxApiDecksDeckIdExportPptxGetResponses,
  ExportVisualApiDecksDeckIdExportKindGetData,
  ExportVisualApiDecksDeckIdExportKindGetErrors,
  ExportVisualApiDecksDeckIdExportKindGetResponses,
  GetAssetApiAssetsAssetIdGetData,
  GetAssetApiAssetsAssetIdGetErrors,
  GetAssetApiAssetsAssetIdGetResponses,
  GetDeckApiDecksDeckIdGetData,
  GetDeckApiDecksDeckIdGetErrors,
  GetDeckApiDecksDeckIdGetResponses,
  GetImageJobApiAssetsJobsJobIdGetData,
  GetImageJobApiAssetsJobsJobIdGetErrors,
  GetImageJobApiAssetsJobsJobIdGetResponses,
  GetJobApiGenerationJobsJobIdGetData,
  GetJobApiGenerationJobsJobIdGetErrors,
  GetJobApiGenerationJobsJobIdGetResponses,
  GetLayoutsApiLayoutsGetData,
  GetLayoutsApiLayoutsGetResponses,
  GetModelCapabilityApiModelsCapabilitiesProviderGetData,
  GetModelCapabilityApiModelsCapabilitiesProviderGetErrors,
  GetModelCapabilityApiModelsCapabilitiesProviderGetResponses,
  GetProviderSettingsApiSettingsProvidersGetData,
  GetProviderSettingsApiSettingsProvidersGetResponses,
  HealthHealthGetData,
  HealthHealthGetResponses,
  ImageJobEventsApiAssetsJobsJobIdEventsGetData,
  ImageJobEventsApiAssetsJobsJobIdEventsGetErrors,
  ImageJobEventsApiAssetsJobsJobIdEventsGetResponses,
  ImportFileApiImportFilePostData,
  ImportFileApiImportFilePostErrors,
  ImportFileApiImportFilePostResponses,
  ImportTextApiImportTextPostData,
  ImportTextApiImportTextPostErrors,
  ImportTextApiImportTextPostResponses,
  ImportUrlApiImportUrlPostData,
  ImportUrlApiImportUrlPostErrors,
  ImportUrlApiImportUrlPostResponses,
  JobEventsApiGenerationJobsJobIdEventsGetData,
  JobEventsApiGenerationJobsJobIdEventsGetErrors,
  JobEventsApiGenerationJobsJobIdEventsGetResponses,
  ListDecksApiDecksGetData,
  ListDecksApiDecksGetResponses,
  ListOllamaModelsApiProvidersOllamaModelsGetData,
  ListOllamaModelsApiProvidersOllamaModelsGetResponses,
  OutlineApiGenerationOutlinePostData,
  OutlineApiGenerationOutlinePostErrors,
  OutlineApiGenerationOutlinePostResponses,
  RecoverJobApiGenerationJobsJobIdRecoverPostData,
  RecoverJobApiGenerationJobsJobIdRecoverPostErrors,
  RecoverJobApiGenerationJobsJobIdRecoverPostResponses,
  RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostData,
  RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostErrors,
  RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostResponses,
  RegenerateImageJobApiAssetsJobsJobIdRegeneratePostData,
  RegenerateImageJobApiAssetsJobsJobIdRegeneratePostErrors,
  RegenerateImageJobApiAssetsJobsJobIdRegeneratePostResponses,
  TestProviderConnectionApiSettingsProvidersTestPostData,
  TestProviderConnectionApiSettingsProvidersTestPostErrors,
  TestProviderConnectionApiSettingsProvidersTestPostResponses,
  UpdateDeckApiDecksDeckIdPatchData,
  UpdateDeckApiDecksDeckIdPatchErrors,
  UpdateDeckApiDecksDeckIdPatchResponses,
  UpdateModelDefaultsApiSettingsModelsPutData,
  UpdateModelDefaultsApiSettingsModelsPutErrors,
  UpdateModelDefaultsApiSettingsModelsPutResponses,
  UpdateProviderSettingsApiSettingsProvidersProviderPutData,
  UpdateProviderSettingsApiSettingsProvidersProviderPutErrors,
  UpdateProviderSettingsApiSettingsProvidersProviderPutResponses,
  UploadAssetApiAssetsUploadPostData,
  UploadAssetApiAssetsUploadPostErrors,
  UploadAssetApiAssetsUploadPostResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * List Decks
 */
export const listDecksApiDecksGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListDecksApiDecksGetData, ThrowOnError>,
): RequestResult<ListDecksApiDecksGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListDecksApiDecksGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/decks", ...options })

/**
 * Create Deck
 */
export const createDeckApiDecksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateDeckApiDecksPostData, ThrowOnError>,
): RequestResult<
  CreateDeckApiDecksPostResponses,
  CreateDeckApiDecksPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateDeckApiDecksPostResponses,
    CreateDeckApiDecksPostErrors,
    ThrowOnError
  >({
    url: "/api/decks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete Deck
 */
export const deleteDeckApiDecksDeckIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDeckApiDecksDeckIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteDeckApiDecksDeckIdDeleteResponses,
  DeleteDeckApiDecksDeckIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteDeckApiDecksDeckIdDeleteResponses,
    DeleteDeckApiDecksDeckIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/decks/{deck_id}", ...options })

/**
 * Get Deck
 */
export const getDeckApiDecksDeckIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetDeckApiDecksDeckIdGetData, ThrowOnError>,
): RequestResult<
  GetDeckApiDecksDeckIdGetResponses,
  GetDeckApiDecksDeckIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDeckApiDecksDeckIdGetResponses,
    GetDeckApiDecksDeckIdGetErrors,
    ThrowOnError
  >({ url: "/api/decks/{deck_id}", ...options })

/**
 * Update Deck
 */
export const updateDeckApiDecksDeckIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateDeckApiDecksDeckIdPatchData, ThrowOnError>,
): RequestResult<
  UpdateDeckApiDecksDeckIdPatchResponses,
  UpdateDeckApiDecksDeckIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateDeckApiDecksDeckIdPatchResponses,
    UpdateDeckApiDecksDeckIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/decks/{deck_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Duplicate Deck
 */
export const duplicateDeckApiDecksDeckIdDuplicatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DuplicateDeckApiDecksDeckIdDuplicatePostData, ThrowOnError>,
): RequestResult<
  DuplicateDeckApiDecksDeckIdDuplicatePostResponses,
  DuplicateDeckApiDecksDeckIdDuplicatePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    DuplicateDeckApiDecksDeckIdDuplicatePostResponses,
    DuplicateDeckApiDecksDeckIdDuplicatePostErrors,
    ThrowOnError
  >({ url: "/api/decks/{deck_id}/duplicate", ...options })

/**
 * Get Model Capability
 */
export const getModelCapabilityApiModelsCapabilitiesProviderGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetModelCapabilityApiModelsCapabilitiesProviderGetData,
    ThrowOnError
  >,
): RequestResult<
  GetModelCapabilityApiModelsCapabilitiesProviderGetResponses,
  GetModelCapabilityApiModelsCapabilitiesProviderGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetModelCapabilityApiModelsCapabilitiesProviderGetResponses,
    GetModelCapabilityApiModelsCapabilitiesProviderGetErrors,
    ThrowOnError
  >({ url: "/api/models/capabilities/{provider}", ...options })

/**
 * Get Provider Settings
 */
export const getProviderSettingsApiSettingsProvidersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetProviderSettingsApiSettingsProvidersGetData,
    ThrowOnError
  >,
): RequestResult<
  GetProviderSettingsApiSettingsProvidersGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetProviderSettingsApiSettingsProvidersGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/settings/providers", ...options })

/**
 * Update Provider Settings
 */
export const updateProviderSettingsApiSettingsProvidersProviderPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateProviderSettingsApiSettingsProvidersProviderPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateProviderSettingsApiSettingsProvidersProviderPutResponses,
  UpdateProviderSettingsApiSettingsProvidersProviderPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProviderSettingsApiSettingsProvidersProviderPutResponses,
    UpdateProviderSettingsApiSettingsProvidersProviderPutErrors,
    ThrowOnError
  >({
    url: "/api/settings/providers/{provider}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update Model Defaults
 */
export const updateModelDefaultsApiSettingsModelsPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateModelDefaultsApiSettingsModelsPutData, ThrowOnError>,
): RequestResult<
  UpdateModelDefaultsApiSettingsModelsPutResponses,
  UpdateModelDefaultsApiSettingsModelsPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateModelDefaultsApiSettingsModelsPutResponses,
    UpdateModelDefaultsApiSettingsModelsPutErrors,
    ThrowOnError
  >({
    url: "/api/settings/models",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Test Provider Connection
 */
export const testProviderConnectionApiSettingsProvidersTestPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TestProviderConnectionApiSettingsProvidersTestPostData,
    ThrowOnError
  >,
): RequestResult<
  TestProviderConnectionApiSettingsProvidersTestPostResponses,
  TestProviderConnectionApiSettingsProvidersTestPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TestProviderConnectionApiSettingsProvidersTestPostResponses,
    TestProviderConnectionApiSettingsProvidersTestPostErrors,
    ThrowOnError
  >({
    url: "/api/settings/providers/test",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List Ollama Models
 */
export const listOllamaModelsApiProvidersOllamaModelsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListOllamaModelsApiProvidersOllamaModelsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListOllamaModelsApiProvidersOllamaModelsGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListOllamaModelsApiProvidersOllamaModelsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/providers/ollama/models", ...options })

/**
 * Outline
 */
export const outlineApiGenerationOutlinePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OutlineApiGenerationOutlinePostData, ThrowOnError>,
): RequestResult<
  OutlineApiGenerationOutlinePostResponses,
  OutlineApiGenerationOutlinePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OutlineApiGenerationOutlinePostResponses,
    OutlineApiGenerationOutlinePostErrors,
    ThrowOnError
  >({
    url: "/api/generation/outline",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Create Job
 */
export const createJobApiGenerationJobsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateJobApiGenerationJobsPostData, ThrowOnError>,
): RequestResult<
  CreateJobApiGenerationJobsPostResponses,
  CreateJobApiGenerationJobsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateJobApiGenerationJobsPostResponses,
    CreateJobApiGenerationJobsPostErrors,
    ThrowOnError
  >({
    url: "/api/generation/jobs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get Job
 */
export const getJobApiGenerationJobsJobIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetJobApiGenerationJobsJobIdGetData, ThrowOnError>,
): RequestResult<
  GetJobApiGenerationJobsJobIdGetResponses,
  GetJobApiGenerationJobsJobIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetJobApiGenerationJobsJobIdGetResponses,
    GetJobApiGenerationJobsJobIdGetErrors,
    ThrowOnError
  >({ url: "/api/generation/jobs/{job_id}", ...options })

/**
 * Recover Job
 */
export const recoverJobApiGenerationJobsJobIdRecoverPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RecoverJobApiGenerationJobsJobIdRecoverPostData,
    ThrowOnError
  >,
): RequestResult<
  RecoverJobApiGenerationJobsJobIdRecoverPostResponses,
  RecoverJobApiGenerationJobsJobIdRecoverPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RecoverJobApiGenerationJobsJobIdRecoverPostResponses,
    RecoverJobApiGenerationJobsJobIdRecoverPostErrors,
    ThrowOnError
  >({ url: "/api/generation/jobs/{job_id}/recover", ...options })

/**
 * Regenerate Card
 */
export const regenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostData,
    ThrowOnError
  >,
): RequestResult<
  RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostResponses,
  RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostResponses,
    RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostErrors,
    ThrowOnError
  >({
    url: "/api/generation/jobs/{job_id}/cards/{card_id}/regenerate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Job Events
 */
export const jobEventsApiGenerationJobsJobIdEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<JobEventsApiGenerationJobsJobIdEventsGetData, ThrowOnError>,
): RequestResult<
  JobEventsApiGenerationJobsJobIdEventsGetResponses,
  JobEventsApiGenerationJobsJobIdEventsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    JobEventsApiGenerationJobsJobIdEventsGetResponses,
    JobEventsApiGenerationJobsJobIdEventsGetErrors,
    ThrowOnError
  >({ url: "/api/generation/jobs/{job_id}/events", ...options })

/**
 * Edit
 */
export const editApiAiEditPost = <ThrowOnError extends boolean = false>(
  options: Options<EditApiAiEditPostData, ThrowOnError>,
): RequestResult<
  EditApiAiEditPostResponses,
  EditApiAiEditPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    EditApiAiEditPostResponses,
    EditApiAiEditPostErrors,
    ThrowOnError
  >({
    url: "/api/ai/edit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Upload Asset
 */
export const uploadAssetApiAssetsUploadPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UploadAssetApiAssetsUploadPostData, ThrowOnError>,
): RequestResult<
  UploadAssetApiAssetsUploadPostResponses,
  UploadAssetApiAssetsUploadPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UploadAssetApiAssetsUploadPostResponses,
    UploadAssetApiAssetsUploadPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/api/assets/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Get Asset
 */
export const getAssetApiAssetsAssetIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAssetApiAssetsAssetIdGetData, ThrowOnError>,
): RequestResult<
  GetAssetApiAssetsAssetIdGetResponses,
  GetAssetApiAssetsAssetIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAssetApiAssetsAssetIdGetResponses,
    GetAssetApiAssetsAssetIdGetErrors,
    ThrowOnError
  >({ url: "/api/assets/{asset_id}", ...options })

/**
 * Create Image Job
 */
export const createImageJobApiAssetsJobsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateImageJobApiAssetsJobsPostData, ThrowOnError>,
): RequestResult<
  CreateImageJobApiAssetsJobsPostResponses,
  CreateImageJobApiAssetsJobsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateImageJobApiAssetsJobsPostResponses,
    CreateImageJobApiAssetsJobsPostErrors,
    ThrowOnError
  >({
    url: "/api/assets/jobs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get Image Job
 */
export const getImageJobApiAssetsJobsJobIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetImageJobApiAssetsJobsJobIdGetData, ThrowOnError>,
): RequestResult<
  GetImageJobApiAssetsJobsJobIdGetResponses,
  GetImageJobApiAssetsJobsJobIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetImageJobApiAssetsJobsJobIdGetResponses,
    GetImageJobApiAssetsJobsJobIdGetErrors,
    ThrowOnError
  >({ url: "/api/assets/jobs/{job_id}", ...options })

/**
 * Regenerate Image Job
 */
export const regenerateImageJobApiAssetsJobsJobIdRegeneratePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RegenerateImageJobApiAssetsJobsJobIdRegeneratePostData,
    ThrowOnError
  >,
): RequestResult<
  RegenerateImageJobApiAssetsJobsJobIdRegeneratePostResponses,
  RegenerateImageJobApiAssetsJobsJobIdRegeneratePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegenerateImageJobApiAssetsJobsJobIdRegeneratePostResponses,
    RegenerateImageJobApiAssetsJobsJobIdRegeneratePostErrors,
    ThrowOnError
  >({ url: "/api/assets/jobs/{job_id}/regenerate", ...options })

/**
 * Image Job Events
 */
export const imageJobEventsApiAssetsJobsJobIdEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ImageJobEventsApiAssetsJobsJobIdEventsGetData, ThrowOnError>,
): RequestResult<
  ImageJobEventsApiAssetsJobsJobIdEventsGetResponses,
  ImageJobEventsApiAssetsJobsJobIdEventsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ImageJobEventsApiAssetsJobsJobIdEventsGetResponses,
    ImageJobEventsApiAssetsJobsJobIdEventsGetErrors,
    ThrowOnError
  >({ url: "/api/assets/jobs/{job_id}/events", ...options })

/**
 * Export Html
 */
export const exportHtmlApiDecksDeckIdExportHtmlGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExportHtmlApiDecksDeckIdExportHtmlGetData, ThrowOnError>,
): RequestResult<
  ExportHtmlApiDecksDeckIdExportHtmlGetResponses,
  ExportHtmlApiDecksDeckIdExportHtmlGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ExportHtmlApiDecksDeckIdExportHtmlGetResponses,
    ExportHtmlApiDecksDeckIdExportHtmlGetErrors,
    ThrowOnError
  >({ url: "/api/decks/{deck_id}/export/html", ...options })

/**
 * Export Visual
 */
export const exportVisualApiDecksDeckIdExportKindGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExportVisualApiDecksDeckIdExportKindGetData, ThrowOnError>,
): RequestResult<
  ExportVisualApiDecksDeckIdExportKindGetResponses,
  ExportVisualApiDecksDeckIdExportKindGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ExportVisualApiDecksDeckIdExportKindGetResponses,
    ExportVisualApiDecksDeckIdExportKindGetErrors,
    ThrowOnError
  >({ url: "/api/decks/{deck_id}/export/{kind}", ...options })

/**
 * Export Pptx
 */
export const exportPptxApiDecksDeckIdExportPptxGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExportPptxApiDecksDeckIdExportPptxGetData, ThrowOnError>,
): RequestResult<
  ExportPptxApiDecksDeckIdExportPptxGetResponses,
  ExportPptxApiDecksDeckIdExportPptxGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ExportPptxApiDecksDeckIdExportPptxGetResponses,
    ExportPptxApiDecksDeckIdExportPptxGetErrors,
    ThrowOnError
  >({ url: "/api/decks/{deck_id}/export/pptx", ...options })

/**
 * Import Text
 */
export const importTextApiImportTextPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ImportTextApiImportTextPostData, ThrowOnError>,
): RequestResult<
  ImportTextApiImportTextPostResponses,
  ImportTextApiImportTextPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ImportTextApiImportTextPostResponses,
    ImportTextApiImportTextPostErrors,
    ThrowOnError
  >({
    url: "/api/import/text",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Import File
 */
export const importFileApiImportFilePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ImportFileApiImportFilePostData, ThrowOnError>,
): RequestResult<
  ImportFileApiImportFilePostResponses,
  ImportFileApiImportFilePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ImportFileApiImportFilePostResponses,
    ImportFileApiImportFilePostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/api/import/file",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Import Url
 */
export const importUrlApiImportUrlPost = <ThrowOnError extends boolean = false>(
  options: Options<ImportUrlApiImportUrlPostData, ThrowOnError>,
): RequestResult<
  ImportUrlApiImportUrlPostResponses,
  ImportUrlApiImportUrlPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ImportUrlApiImportUrlPostResponses,
    ImportUrlApiImportUrlPostErrors,
    ThrowOnError
  >({
    url: "/api/import/url",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthGetData, ThrowOnError>,
): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options })

/**
 * Get Layouts
 */
export const getLayoutsApiLayoutsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetLayoutsApiLayoutsGetData, ThrowOnError>,
): RequestResult<GetLayoutsApiLayoutsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetLayoutsApiLayoutsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/layouts", ...options })
