// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://.openapi.json` | (string & {})
}

/**
 * AIEditRequest
 */
export type AiEditRequest = {
  /**
   * Deck Id
   */
  deck_id: string
  /**
   * Card Id
   */
  card_id: string
  /**
   * Block Index
   */
  block_index: number
  /**
   * Action
   */
  action: "rewrite" | "shorten" | "expand" | "translate" | "tone"
  /**
   * Instruction
   */
  instruction?: string
}

/**
 * AIEditResponse
 */
export type AiEditResponse = {
  /**
   * Text
   */
  text: string
  /**
   * Action
   */
  action: string
}

/**
 * AddCardOperation
 */
export type AddCardOperation = {
  /**
   * Op
   */
  op: "add_card"
  card: Card
  /**
   * Index
   */
  index?: number | null
}

/**
 * AgentPreview
 */
export type AgentPreview = {
  deck: DeckDocument
  /**
   * Operations
   */
  operations: Array<
    | AddCardOperation
    | UpdateBlockOperation
    | MoveCardOperation
    | DeleteCardOperation
    | SetLayoutOperation
    | SetThemeOperation
  >
  /**
   * Requires Confirmation
   */
  requires_confirmation?: boolean
  /**
   * Warnings
   */
  warnings?: Array<string>
}

/**
 * AgentRequest
 */
export type AgentRequest = {
  deck: DeckDocument
  /**
   * Message
   */
  message: string
  /**
   * Operations
   */
  operations?: Array<
    | AddCardOperation
    | UpdateBlockOperation
    | MoveCardOperation
    | DeleteCardOperation
    | SetLayoutOperation
    | SetThemeOperation
  > | null
  /**
   * Confirm Deletions
   */
  confirm_deletions?: boolean
}

/**
 * AppInfoResponse
 */
export type AppInfoResponse = {
  /**
   * Version
   */
  version: string
  /**
   * Data Directory
   */
  data_directory: string
  /**
   * Ollama Base Url
   */
  ollama_base_url: string
}

/**
 * Body_import_file_api_import_file_post
 */
export type BodyImportFileApiImportFilePost = {
  /**
   * File
   */
  file: Blob | File
}

/**
 * Body_upload_asset_api_assets_upload_post
 */
export type BodyUploadAssetApiAssetsUploadPost = {
  /**
   * File
   */
  file: Blob | File
}

/**
 * BulletsBlock
 */
export type BulletsBlock = {
  /**
   * Type
   */
  type: "bullets"
  /**
   * Items
   */
  items: Array<string>
}

/**
 * Card
 */
export type Card = {
  /**
   * Id
   */
  id?: string
  /**
   * Title
   */
  title: string
  layout: Layout
  /**
   * Blocks
   */
  blocks: Array<
    | HeadingBlock
    | ParagraphBlock
    | BulletsBlock
    | ColumnsBlock
    | QuoteBlock
    | StatBlock
    | TableBlock
    | ImageBlock
    | ChartBlock
    | MermaidBlock
    | IconBlock
  >
}

/**
 * ChartBlock
 */
export type ChartBlock = {
  /**
   * Type
   */
  type: "chart"
  /**
   * Title
   */
  title: string
  /**
   * Labels
   */
  labels: Array<string>
  /**
   * Values
   */
  values: Array<number>
  /**
   * Illustrative
   */
  illustrative?: boolean
}

/**
 * ColumnContent
 */
export type ColumnContent = {
  /**
   * Title
   */
  title: string
  /**
   * Body
   */
  body: string
}

/**
 * ColumnsBlock
 */
export type ColumnsBlock = {
  /**
   * Type
   */
  type: "columns"
  /**
   * Columns
   */
  columns: Array<ColumnContent>
}

/**
 * DeckCreate
 */
export type DeckCreate = {
  /**
   * Title
   */
  title: string
  theme?: Theme
  /**
   * Cards
   */
  cards: Array<Card>
}

/**
 * DeckDocument
 */
export type DeckDocument = {
  /**
   * Title
   */
  title: string
  theme: Theme
  /**
   * Cards
   */
  cards: Array<Card>
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Version
   */
  version?: number
}

/**
 * DeckUpdate
 */
export type DeckUpdate = {
  /**
   * Title
   */
  title?: string | null
  theme?: Theme | null
  /**
   * Cards
   */
  cards?: Array<Card> | null
  /**
   * Version
   */
  version?: number | null
}

/**
 * DeleteCardOperation
 */
export type DeleteCardOperation = {
  /**
   * Op
   */
  op: "delete_card"
  /**
   * Card Id
   */
  card_id: string
  /**
   * Confirmed
   */
  confirmed?: boolean
}

/**
 * GenerationJobCreate
 */
export type GenerationJobCreate = {
  /**
   * Prompt
   */
  prompt: string
  settings?: GenerationSettings
  outline?: Outline | null
}

/**
 * GenerationJobStatus
 */
export type GenerationJobStatus = {
  /**
   * Id
   */
  id: string
  /**
   * Status
   */
  status: "queued" | "running" | "completed" | "partial" | "failed"
  /**
   * Progress
   */
  progress: number
  outline?: Outline | null
  /**
   * Cards
   */
  cards?: Array<Card>
  /**
   * Errors
   */
  errors?: Array<string>
  /**
   * Deck Id
   */
  deck_id?: string | null
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * GenerationSettings
 */
export type GenerationSettings = {
  /**
   * Card Count
   */
  card_count?: number
  /**
   * Tone
   */
  tone?: string
  /**
   * Language
   */
  language?: string
  /**
   * Audience
   */
  audience?: string
  /**
   * Density
   */
  density?: "concise" | "balanced" | "detailed"
  /**
   * Concurrency
   */
  concurrency?: number
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * HeadingBlock
 */
export type HeadingBlock = {
  /**
   * Type
   */
  type: "heading"
  /**
   * Text
   */
  text: string
  /**
   * Level
   */
  level?: number
}

/**
 * HealthResponse
 */
export type HealthResponse = {
  /**
   * Status
   */
  status: string
}

/**
 * IconBlock
 */
export type IconBlock = {
  /**
   * Type
   */
  type: "icon"
  /**
   * Name
   */
  name: string
  /**
   * Label
   */
  label?: string | null
}

/**
 * ImageBlock
 */
export type ImageBlock = {
  /**
   * Type
   */
  type: "image"
  /**
   * Prompt
   */
  prompt: string
  /**
   * Asset Id
   */
  asset_id?: string | null
  /**
   * Alt
   */
  alt?: string
}

/**
 * ImageJob
 */
export type ImageJob = {
  /**
   * Id
   */
  id: string
  /**
   * Status
   */
  status: string
  /**
   * Asset Id
   */
  asset_id?: string | null
  /**
   * Error
   */
  error?: string | null
}

/**
 * ImageJobCreate
 */
export type ImageJobCreate = {
  /**
   * Prompt
   */
  prompt: string
  /**
   * Size
   */
  size?: string
}

/**
 * Layout
 */
export type Layout =
  | "title"
  | "single_column"
  | "two_column"
  | "three_column"
  | "image_left"
  | "image_right"
  | "quote"
  | "timeline"

/**
 * MermaidBlock
 */
export type MermaidBlock = {
  /**
   * Type
   */
  type: "mermaid"
  /**
   * Code
   */
  code: string
  /**
   * Caption
   */
  caption?: string | null
}

/**
 * ModelCapabilitiesResponse
 */
export type ModelCapabilitiesResponse = {
  /**
   * Provider
   */
  provider: "gemini" | "anthropic" | "xai" | "openai_compatible" | "ollama"
  /**
   * Model
   */
  model: string
  /**
   * Json Schema
   */
  json_schema: boolean
  /**
   * Json Mode
   */
  json_mode: boolean
  /**
   * Tools
   */
  tools: boolean
  /**
   * Context Window
   */
  context_window: number | null
  /**
   * Output Modes
   */
  output_modes: Array<string>
}

/**
 * ModelDefaultsUpdate
 */
export type ModelDefaultsUpdate = {
  outline: ProviderModelSelection | null
  content: ProviderModelSelection | null
  edit: ProviderModelSelection | null
}

/**
 * MoveCardOperation
 */
export type MoveCardOperation = {
  /**
   * Op
   */
  op: "move_card"
  /**
   * Card Id
   */
  card_id: string
  /**
   * To Index
   */
  to_index: number
}

/**
 * OllamaModel
 */
export type OllamaModel = {
  /**
   * Name
   */
  name: string
  /**
   * Size
   */
  size?: number | null
  /**
   * Modified At
   */
  modified_at?: string | null
}

/**
 * OllamaModelsResponse
 */
export type OllamaModelsResponse = {
  /**
   * Models
   */
  models: Array<OllamaModel>
}

/**
 * Outline
 */
export type Outline = {
  /**
   * Title
   */
  title: string
  /**
   * Items
   */
  items: Array<OutlineItem>
}

/**
 * OutlineItem
 */
export type OutlineItem = {
  /**
   * Id
   */
  id: string
  /**
   * Title
   */
  title: string
  /**
   * Summary
   */
  summary: string
}

/**
 * OutlineRequest
 */
export type OutlineRequest = {
  /**
   * Prompt
   */
  prompt: string
  settings?: GenerationSettings
}

/**
 * ParagraphBlock
 */
export type ParagraphBlock = {
  /**
   * Type
   */
  type: "paragraph"
  /**
   * Text
   */
  text: string
}

/**
 * ProviderConfigUpdate
 */
export type ProviderConfigUpdate = {
  /**
   * Model
   */
  model: string
  /**
   * Api Key
   */
  api_key?: string | null
  /**
   * Clear Api Key
   */
  clear_api_key?: boolean
  /**
   * Base Url
   */
  base_url?: string | null
}

/**
 * ProviderConfiguration
 */
export type ProviderConfiguration = {
  /**
   * Provider
   */
  provider: "gemini" | "anthropic" | "xai" | "openai_compatible" | "ollama"
  /**
   * Configured
   */
  configured: boolean
  /**
   * Model
   */
  model: string | null
  /**
   * Base Url
   */
  base_url: string | null
  /**
   * Api Key Configured
   */
  api_key_configured: boolean
}

/**
 * ProviderModelSelection
 */
export type ProviderModelSelection = {
  /**
   * Provider
   */
  provider: "gemini" | "anthropic" | "xai" | "openai_compatible" | "ollama"
  /**
   * Model
   */
  model: string
}

/**
 * ProviderSettingsResponse
 */
export type ProviderSettingsResponse = {
  /**
   * Providers
   */
  providers: Array<ProviderConfiguration>
  /**
   * Defaults
   */
  defaults: {
    [key: string]: ProviderModelSelection | null
  }
}

/**
 * ProviderTestRequest
 */
export type ProviderTestRequest = {
  /**
   * Provider
   */
  provider: "gemini" | "anthropic" | "xai" | "openai_compatible" | "ollama"
  /**
   * Model
   */
  model?: string | null
}

/**
 * ProviderTestResponse
 */
export type ProviderTestResponse = {
  /**
   * Ok
   */
  ok: boolean
  /**
   * Message
   */
  message: string
}

/**
 * QuoteBlock
 */
export type QuoteBlock = {
  /**
   * Type
   */
  type: "quote"
  /**
   * Text
   */
  text: string
  /**
   * Attribution
   */
  attribution?: string | null
}

/**
 * RegenerateCardRequest
 */
export type RegenerateCardRequest = {
  /**
   * Prompt
   */
  prompt?: string | null
  settings?: GenerationSettings | null
}

/**
 * SetLayoutOperation
 */
export type SetLayoutOperation = {
  /**
   * Op
   */
  op: "set_layout"
  /**
   * Card Id
   */
  card_id: string
  layout: Layout
}

/**
 * SetThemeOperation
 */
export type SetThemeOperation = {
  /**
   * Op
   */
  op: "set_theme"
  theme: Theme
}

/**
 * StatBlock
 */
export type StatBlock = {
  /**
   * Type
   */
  type: "stat"
  /**
   * Value
   */
  value: string
  /**
   * Label
   */
  label: string
  /**
   * Context
   */
  context?: string | null
}

/**
 * TableBlock
 */
export type TableBlock = {
  /**
   * Type
   */
  type: "table"
  /**
   * Headers
   */
  headers: Array<string>
  /**
   * Rows
   */
  rows: Array<Array<string>>
}

/**
 * TextImport
 */
export type TextImport = {
  /**
   * Text
   */
  text: string
}

/**
 * Theme
 */
export type Theme = "ocean" | "sunset" | "forest"

/**
 * UpdateBlockOperation
 */
export type UpdateBlockOperation = {
  /**
   * Op
   */
  op: "update_block"
  /**
   * Card Id
   */
  card_id: string
  /**
   * Block Index
   */
  block_index: number
  /**
   * Block
   */
  block:
    | ({
        type: "heading"
      } & HeadingBlock)
    | ({
        type: "paragraph"
      } & ParagraphBlock)
    | ({
        type: "bullets"
      } & BulletsBlock)
    | ({
        type: "columns"
      } & ColumnsBlock)
    | ({
        type: "quote"
      } & QuoteBlock)
    | ({
        type: "stat"
      } & StatBlock)
    | ({
        type: "table"
      } & TableBlock)
    | ({
        type: "image"
      } & ImageBlock)
    | ({
        type: "chart"
      } & ChartBlock)
    | ({
        type: "mermaid"
      } & MermaidBlock)
    | ({
        type: "icon"
      } & IconBlock)
}

/**
 * UpdateCheckResponse
 */
export type UpdateCheckResponse = {
  /**
   * Current Version
   */
  current_version: string
  /**
   * Latest Version
   */
  latest_version?: string | null
  /**
   * Release Url
   */
  release_url?: string | null
  /**
   * Available
   */
  available?: boolean
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type ListDecksApiDecksGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/decks"
}

export type ListDecksApiDecksGetResponses = {
  /**
   * Response List Decks Api Decks Get
   *
   * Successful Response
   */
  200: Array<DeckDocument>
}

export type ListDecksApiDecksGetResponse =
  ListDecksApiDecksGetResponses[keyof ListDecksApiDecksGetResponses]

export type CreateDeckApiDecksPostData = {
  body: DeckCreate
  path?: never
  query?: never
  url: "/api/decks"
}

export type CreateDeckApiDecksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateDeckApiDecksPostError =
  CreateDeckApiDecksPostErrors[keyof CreateDeckApiDecksPostErrors]

export type CreateDeckApiDecksPostResponses = {
  /**
   * Successful Response
   */
  201: DeckDocument
}

export type CreateDeckApiDecksPostResponse =
  CreateDeckApiDecksPostResponses[keyof CreateDeckApiDecksPostResponses]

export type DeleteDeckApiDecksDeckIdDeleteData = {
  body?: never
  path: {
    /**
     * Deck Id
     */
    deck_id: string
  }
  query?: never
  url: "/api/decks/{deck_id}"
}

export type DeleteDeckApiDecksDeckIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteDeckApiDecksDeckIdDeleteError =
  DeleteDeckApiDecksDeckIdDeleteErrors[keyof DeleteDeckApiDecksDeckIdDeleteErrors]

export type DeleteDeckApiDecksDeckIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteDeckApiDecksDeckIdDeleteResponse =
  DeleteDeckApiDecksDeckIdDeleteResponses[keyof DeleteDeckApiDecksDeckIdDeleteResponses]

export type GetDeckApiDecksDeckIdGetData = {
  body?: never
  path: {
    /**
     * Deck Id
     */
    deck_id: string
  }
  query?: never
  url: "/api/decks/{deck_id}"
}

export type GetDeckApiDecksDeckIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetDeckApiDecksDeckIdGetError =
  GetDeckApiDecksDeckIdGetErrors[keyof GetDeckApiDecksDeckIdGetErrors]

export type GetDeckApiDecksDeckIdGetResponses = {
  /**
   * Successful Response
   */
  200: DeckDocument
}

export type GetDeckApiDecksDeckIdGetResponse =
  GetDeckApiDecksDeckIdGetResponses[keyof GetDeckApiDecksDeckIdGetResponses]

export type UpdateDeckApiDecksDeckIdPatchData = {
  body: DeckUpdate
  path: {
    /**
     * Deck Id
     */
    deck_id: string
  }
  query?: never
  url: "/api/decks/{deck_id}"
}

export type UpdateDeckApiDecksDeckIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateDeckApiDecksDeckIdPatchError =
  UpdateDeckApiDecksDeckIdPatchErrors[keyof UpdateDeckApiDecksDeckIdPatchErrors]

export type UpdateDeckApiDecksDeckIdPatchResponses = {
  /**
   * Successful Response
   */
  200: DeckDocument
}

export type UpdateDeckApiDecksDeckIdPatchResponse =
  UpdateDeckApiDecksDeckIdPatchResponses[keyof UpdateDeckApiDecksDeckIdPatchResponses]

export type DuplicateDeckApiDecksDeckIdDuplicatePostData = {
  body?: never
  path: {
    /**
     * Deck Id
     */
    deck_id: string
  }
  query?: never
  url: "/api/decks/{deck_id}/duplicate"
}

export type DuplicateDeckApiDecksDeckIdDuplicatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DuplicateDeckApiDecksDeckIdDuplicatePostError =
  DuplicateDeckApiDecksDeckIdDuplicatePostErrors[keyof DuplicateDeckApiDecksDeckIdDuplicatePostErrors]

export type DuplicateDeckApiDecksDeckIdDuplicatePostResponses = {
  /**
   * Successful Response
   */
  201: DeckDocument
}

export type DuplicateDeckApiDecksDeckIdDuplicatePostResponse =
  DuplicateDeckApiDecksDeckIdDuplicatePostResponses[keyof DuplicateDeckApiDecksDeckIdDuplicatePostResponses]

export type GetAppInfoApiSettingsAppGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/settings/app"
}

export type GetAppInfoApiSettingsAppGetResponses = {
  /**
   * Successful Response
   */
  200: AppInfoResponse
}

export type GetAppInfoApiSettingsAppGetResponse =
  GetAppInfoApiSettingsAppGetResponses[keyof GetAppInfoApiSettingsAppGetResponses]

export type CheckForUpdateApiUpdatesCheckGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/updates/check"
}

export type CheckForUpdateApiUpdatesCheckGetResponses = {
  /**
   * Successful Response
   */
  200: UpdateCheckResponse
}

export type CheckForUpdateApiUpdatesCheckGetResponse =
  CheckForUpdateApiUpdatesCheckGetResponses[keyof CheckForUpdateApiUpdatesCheckGetResponses]

export type GetModelCapabilityApiModelsCapabilitiesProviderGetData = {
  body?: never
  path: {
    /**
     * Provider
     */
    provider: "gemini" | "anthropic" | "xai" | "openai_compatible" | "ollama"
  }
  query: {
    /**
     * Model
     */
    model: string
  }
  url: "/api/models/capabilities/{provider}"
}

export type GetModelCapabilityApiModelsCapabilitiesProviderGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetModelCapabilityApiModelsCapabilitiesProviderGetError =
  GetModelCapabilityApiModelsCapabilitiesProviderGetErrors[keyof GetModelCapabilityApiModelsCapabilitiesProviderGetErrors]

export type GetModelCapabilityApiModelsCapabilitiesProviderGetResponses = {
  /**
   * Successful Response
   */
  200: ModelCapabilitiesResponse
}

export type GetModelCapabilityApiModelsCapabilitiesProviderGetResponse =
  GetModelCapabilityApiModelsCapabilitiesProviderGetResponses[keyof GetModelCapabilityApiModelsCapabilitiesProviderGetResponses]

export type GetProviderSettingsApiSettingsProvidersGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/settings/providers"
}

export type GetProviderSettingsApiSettingsProvidersGetResponses = {
  /**
   * Successful Response
   */
  200: ProviderSettingsResponse
}

export type GetProviderSettingsApiSettingsProvidersGetResponse =
  GetProviderSettingsApiSettingsProvidersGetResponses[keyof GetProviderSettingsApiSettingsProvidersGetResponses]

export type UpdateProviderSettingsApiSettingsProvidersProviderPutData = {
  body: ProviderConfigUpdate
  path: {
    /**
     * Provider
     */
    provider: "gemini" | "anthropic" | "xai" | "openai_compatible" | "ollama"
  }
  query?: never
  url: "/api/settings/providers/{provider}"
}

export type UpdateProviderSettingsApiSettingsProvidersProviderPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateProviderSettingsApiSettingsProvidersProviderPutError =
  UpdateProviderSettingsApiSettingsProvidersProviderPutErrors[keyof UpdateProviderSettingsApiSettingsProvidersProviderPutErrors]

export type UpdateProviderSettingsApiSettingsProvidersProviderPutResponses = {
  /**
   * Successful Response
   */
  200: ProviderConfiguration
}

export type UpdateProviderSettingsApiSettingsProvidersProviderPutResponse =
  UpdateProviderSettingsApiSettingsProvidersProviderPutResponses[keyof UpdateProviderSettingsApiSettingsProvidersProviderPutResponses]

export type UpdateModelDefaultsApiSettingsModelsPutData = {
  body: ModelDefaultsUpdate
  path?: never
  query?: never
  url: "/api/settings/models"
}

export type UpdateModelDefaultsApiSettingsModelsPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateModelDefaultsApiSettingsModelsPutError =
  UpdateModelDefaultsApiSettingsModelsPutErrors[keyof UpdateModelDefaultsApiSettingsModelsPutErrors]

export type UpdateModelDefaultsApiSettingsModelsPutResponses = {
  /**
   * Successful Response
   */
  200: ProviderSettingsResponse
}

export type UpdateModelDefaultsApiSettingsModelsPutResponse =
  UpdateModelDefaultsApiSettingsModelsPutResponses[keyof UpdateModelDefaultsApiSettingsModelsPutResponses]

export type TestProviderConnectionApiSettingsProvidersTestPostData = {
  body: ProviderTestRequest
  path?: never
  query?: never
  url: "/api/settings/providers/test"
}

export type TestProviderConnectionApiSettingsProvidersTestPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TestProviderConnectionApiSettingsProvidersTestPostError =
  TestProviderConnectionApiSettingsProvidersTestPostErrors[keyof TestProviderConnectionApiSettingsProvidersTestPostErrors]

export type TestProviderConnectionApiSettingsProvidersTestPostResponses = {
  /**
   * Successful Response
   */
  200: ProviderTestResponse
}

export type TestProviderConnectionApiSettingsProvidersTestPostResponse =
  TestProviderConnectionApiSettingsProvidersTestPostResponses[keyof TestProviderConnectionApiSettingsProvidersTestPostResponses]

export type ListOllamaModelsApiProvidersOllamaModelsGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/providers/ollama/models"
}

export type ListOllamaModelsApiProvidersOllamaModelsGetResponses = {
  /**
   * Successful Response
   */
  200: OllamaModelsResponse
}

export type ListOllamaModelsApiProvidersOllamaModelsGetResponse =
  ListOllamaModelsApiProvidersOllamaModelsGetResponses[keyof ListOllamaModelsApiProvidersOllamaModelsGetResponses]

export type OutlineApiGenerationOutlinePostData = {
  body: OutlineRequest
  path?: never
  query?: never
  url: "/api/generation/outline"
}

export type OutlineApiGenerationOutlinePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type OutlineApiGenerationOutlinePostError =
  OutlineApiGenerationOutlinePostErrors[keyof OutlineApiGenerationOutlinePostErrors]

export type OutlineApiGenerationOutlinePostResponses = {
  /**
   * Successful Response
   */
  200: Outline
}

export type OutlineApiGenerationOutlinePostResponse =
  OutlineApiGenerationOutlinePostResponses[keyof OutlineApiGenerationOutlinePostResponses]

export type CreateJobApiGenerationJobsPostData = {
  body: GenerationJobCreate
  path?: never
  query?: never
  url: "/api/generation/jobs"
}

export type CreateJobApiGenerationJobsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateJobApiGenerationJobsPostError =
  CreateJobApiGenerationJobsPostErrors[keyof CreateJobApiGenerationJobsPostErrors]

export type CreateJobApiGenerationJobsPostResponses = {
  /**
   * Successful Response
   */
  202: GenerationJobStatus
}

export type CreateJobApiGenerationJobsPostResponse =
  CreateJobApiGenerationJobsPostResponses[keyof CreateJobApiGenerationJobsPostResponses]

export type GetJobApiGenerationJobsJobIdGetData = {
  body?: never
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: "/api/generation/jobs/{job_id}"
}

export type GetJobApiGenerationJobsJobIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetJobApiGenerationJobsJobIdGetError =
  GetJobApiGenerationJobsJobIdGetErrors[keyof GetJobApiGenerationJobsJobIdGetErrors]

export type GetJobApiGenerationJobsJobIdGetResponses = {
  /**
   * Successful Response
   */
  200: GenerationJobStatus
}

export type GetJobApiGenerationJobsJobIdGetResponse =
  GetJobApiGenerationJobsJobIdGetResponses[keyof GetJobApiGenerationJobsJobIdGetResponses]

export type RecoverJobApiGenerationJobsJobIdRecoverPostData = {
  body?: never
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: "/api/generation/jobs/{job_id}/recover"
}

export type RecoverJobApiGenerationJobsJobIdRecoverPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RecoverJobApiGenerationJobsJobIdRecoverPostError =
  RecoverJobApiGenerationJobsJobIdRecoverPostErrors[keyof RecoverJobApiGenerationJobsJobIdRecoverPostErrors]

export type RecoverJobApiGenerationJobsJobIdRecoverPostResponses = {
  /**
   * Successful Response
   */
  200: GenerationJobStatus
}

export type RecoverJobApiGenerationJobsJobIdRecoverPostResponse =
  RecoverJobApiGenerationJobsJobIdRecoverPostResponses[keyof RecoverJobApiGenerationJobsJobIdRecoverPostResponses]

export type RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostData =
  {
    body: RegenerateCardRequest
    path: {
      /**
       * Job Id
       */
      job_id: string
      /**
       * Card Id
       */
      card_id: string
    }
    query?: never
    url: "/api/generation/jobs/{job_id}/cards/{card_id}/regenerate"
  }

export type RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError
  }

export type RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostError =
  RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostErrors[keyof RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostErrors]

export type RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostResponses =
  {
    /**
     * Successful Response
     */
    200: GenerationJobStatus
  }

export type RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostResponse =
  RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostResponses[keyof RegenerateCardApiGenerationJobsJobIdCardsCardIdRegeneratePostResponses]

export type JobEventsApiGenerationJobsJobIdEventsGetData = {
  body?: never
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: "/api/generation/jobs/{job_id}/events"
}

export type JobEventsApiGenerationJobsJobIdEventsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type JobEventsApiGenerationJobsJobIdEventsGetError =
  JobEventsApiGenerationJobsJobIdEventsGetErrors[keyof JobEventsApiGenerationJobsJobIdEventsGetErrors]

export type JobEventsApiGenerationJobsJobIdEventsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type EditApiAiEditPostData = {
  body: AiEditRequest
  path?: never
  query?: never
  url: "/api/ai/edit"
}

export type EditApiAiEditPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type EditApiAiEditPostError =
  EditApiAiEditPostErrors[keyof EditApiAiEditPostErrors]

export type EditApiAiEditPostResponses = {
  /**
   * Successful Response
   */
  200: AiEditResponse
}

export type EditApiAiEditPostResponse =
  EditApiAiEditPostResponses[keyof EditApiAiEditPostResponses]

export type PreviewApiAgentPreviewPostData = {
  body: AgentRequest
  path?: never
  query?: never
  url: "/api/agent/preview"
}

export type PreviewApiAgentPreviewPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PreviewApiAgentPreviewPostError =
  PreviewApiAgentPreviewPostErrors[keyof PreviewApiAgentPreviewPostErrors]

export type PreviewApiAgentPreviewPostResponses = {
  /**
   * Successful Response
   */
  200: AgentPreview
}

export type PreviewApiAgentPreviewPostResponse =
  PreviewApiAgentPreviewPostResponses[keyof PreviewApiAgentPreviewPostResponses]

export type UploadAssetApiAssetsUploadPostData = {
  body: BodyUploadAssetApiAssetsUploadPost
  path?: never
  query?: never
  url: "/api/assets/upload"
}

export type UploadAssetApiAssetsUploadPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UploadAssetApiAssetsUploadPostError =
  UploadAssetApiAssetsUploadPostErrors[keyof UploadAssetApiAssetsUploadPostErrors]

export type UploadAssetApiAssetsUploadPostResponses = {
  /**
   * Response Upload Asset Api Assets Upload Post
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type UploadAssetApiAssetsUploadPostResponse =
  UploadAssetApiAssetsUploadPostResponses[keyof UploadAssetApiAssetsUploadPostResponses]

export type GetAssetApiAssetsAssetIdGetData = {
  body?: never
  path: {
    /**
     * Asset Id
     */
    asset_id: string
  }
  query?: never
  url: "/api/assets/{asset_id}"
}

export type GetAssetApiAssetsAssetIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetAssetApiAssetsAssetIdGetError =
  GetAssetApiAssetsAssetIdGetErrors[keyof GetAssetApiAssetsAssetIdGetErrors]

export type GetAssetApiAssetsAssetIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type CreateImageJobApiAssetsJobsPostData = {
  body: ImageJobCreate
  path?: never
  query?: never
  url: "/api/assets/jobs"
}

export type CreateImageJobApiAssetsJobsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateImageJobApiAssetsJobsPostError =
  CreateImageJobApiAssetsJobsPostErrors[keyof CreateImageJobApiAssetsJobsPostErrors]

export type CreateImageJobApiAssetsJobsPostResponses = {
  /**
   * Successful Response
   */
  202: ImageJob
}

export type CreateImageJobApiAssetsJobsPostResponse =
  CreateImageJobApiAssetsJobsPostResponses[keyof CreateImageJobApiAssetsJobsPostResponses]

export type GetImageJobApiAssetsJobsJobIdGetData = {
  body?: never
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: "/api/assets/jobs/{job_id}"
}

export type GetImageJobApiAssetsJobsJobIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetImageJobApiAssetsJobsJobIdGetError =
  GetImageJobApiAssetsJobsJobIdGetErrors[keyof GetImageJobApiAssetsJobsJobIdGetErrors]

export type GetImageJobApiAssetsJobsJobIdGetResponses = {
  /**
   * Successful Response
   */
  200: ImageJob
}

export type GetImageJobApiAssetsJobsJobIdGetResponse =
  GetImageJobApiAssetsJobsJobIdGetResponses[keyof GetImageJobApiAssetsJobsJobIdGetResponses]

export type RegenerateImageJobApiAssetsJobsJobIdRegeneratePostData = {
  body?: never
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: "/api/assets/jobs/{job_id}/regenerate"
}

export type RegenerateImageJobApiAssetsJobsJobIdRegeneratePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RegenerateImageJobApiAssetsJobsJobIdRegeneratePostError =
  RegenerateImageJobApiAssetsJobsJobIdRegeneratePostErrors[keyof RegenerateImageJobApiAssetsJobsJobIdRegeneratePostErrors]

export type RegenerateImageJobApiAssetsJobsJobIdRegeneratePostResponses = {
  /**
   * Successful Response
   */
  202: ImageJob
}

export type RegenerateImageJobApiAssetsJobsJobIdRegeneratePostResponse =
  RegenerateImageJobApiAssetsJobsJobIdRegeneratePostResponses[keyof RegenerateImageJobApiAssetsJobsJobIdRegeneratePostResponses]

export type ImageJobEventsApiAssetsJobsJobIdEventsGetData = {
  body?: never
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: "/api/assets/jobs/{job_id}/events"
}

export type ImageJobEventsApiAssetsJobsJobIdEventsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImageJobEventsApiAssetsJobsJobIdEventsGetError =
  ImageJobEventsApiAssetsJobsJobIdEventsGetErrors[keyof ImageJobEventsApiAssetsJobsJobIdEventsGetErrors]

export type ImageJobEventsApiAssetsJobsJobIdEventsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ExportHtmlApiDecksDeckIdExportHtmlGetData = {
  body?: never
  path: {
    /**
     * Deck Id
     */
    deck_id: string
  }
  query?: never
  url: "/api/decks/{deck_id}/export/html"
}

export type ExportHtmlApiDecksDeckIdExportHtmlGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ExportHtmlApiDecksDeckIdExportHtmlGetError =
  ExportHtmlApiDecksDeckIdExportHtmlGetErrors[keyof ExportHtmlApiDecksDeckIdExportHtmlGetErrors]

export type ExportHtmlApiDecksDeckIdExportHtmlGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ExportVisualApiDecksDeckIdExportKindGetData = {
  body?: never
  path: {
    /**
     * Deck Id
     */
    deck_id: string
    /**
     * Kind
     */
    kind: string
  }
  query?: never
  url: "/api/decks/{deck_id}/export/{kind}"
}

export type ExportVisualApiDecksDeckIdExportKindGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ExportVisualApiDecksDeckIdExportKindGetError =
  ExportVisualApiDecksDeckIdExportKindGetErrors[keyof ExportVisualApiDecksDeckIdExportKindGetErrors]

export type ExportVisualApiDecksDeckIdExportKindGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ExportPptxApiDecksDeckIdExportPptxGetData = {
  body?: never
  path: {
    /**
     * Deck Id
     */
    deck_id: string
  }
  query?: never
  url: "/api/decks/{deck_id}/export/pptx"
}

export type ExportPptxApiDecksDeckIdExportPptxGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ExportPptxApiDecksDeckIdExportPptxGetError =
  ExportPptxApiDecksDeckIdExportPptxGetErrors[keyof ExportPptxApiDecksDeckIdExportPptxGetErrors]

export type ExportPptxApiDecksDeckIdExportPptxGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ImportTextApiImportTextPostData = {
  body: TextImport
  path?: never
  query?: never
  url: "/api/import/text"
}

export type ImportTextApiImportTextPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImportTextApiImportTextPostError =
  ImportTextApiImportTextPostErrors[keyof ImportTextApiImportTextPostErrors]

export type ImportTextApiImportTextPostResponses = {
  /**
   * Successful Response
   */
  200: Outline
}

export type ImportTextApiImportTextPostResponse =
  ImportTextApiImportTextPostResponses[keyof ImportTextApiImportTextPostResponses]

export type ImportFileApiImportFilePostData = {
  body: BodyImportFileApiImportFilePost
  path?: never
  query?: never
  url: "/api/import/file"
}

export type ImportFileApiImportFilePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImportFileApiImportFilePostError =
  ImportFileApiImportFilePostErrors[keyof ImportFileApiImportFilePostErrors]

export type ImportFileApiImportFilePostResponses = {
  /**
   * Successful Response
   */
  200: Outline
}

export type ImportFileApiImportFilePostResponse =
  ImportFileApiImportFilePostResponses[keyof ImportFileApiImportFilePostResponses]

export type ImportUrlApiImportUrlPostData = {
  /**
   * Payload
   */
  body: {
    [key: string]: string
  }
  path?: never
  query?: never
  url: "/api/import/url"
}

export type ImportUrlApiImportUrlPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImportUrlApiImportUrlPostError =
  ImportUrlApiImportUrlPostErrors[keyof ImportUrlApiImportUrlPostErrors]

export type ImportUrlApiImportUrlPostResponses = {
  /**
   * Successful Response
   */
  200: Outline
}

export type ImportUrlApiImportUrlPostResponse =
  ImportUrlApiImportUrlPostResponses[keyof ImportUrlApiImportUrlPostResponses]

export type HealthHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: "/health"
}

export type HealthHealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse
}

export type HealthHealthGetResponse =
  HealthHealthGetResponses[keyof HealthHealthGetResponses]

export type GetLayoutsApiLayoutsGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/layouts"
}

export type GetLayoutsApiLayoutsGetResponses = {
  /**
   * Response Get Layouts Api Layouts Get
   *
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown
  }>
}

export type GetLayoutsApiLayoutsGetResponse =
  GetLayoutsApiLayoutsGetResponses[keyof GetLayoutsApiLayoutsGetResponses]
