from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from pathlib import Path
from uuid import uuid4

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from fastapi.responses import FileResponse, StreamingResponse
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.paths import assets_directory
from app.database import get_session, session_factory
from app.models.image import ImageJobRecord
from app.services.images import (
    A1111ImageProvider,
    ComfyUIProvider,
    OpenAICompatibleImageProvider,
    StockImageProvider,
    fallback_image,
    image_extension,
)

router = APIRouter(prefix="/api/assets", tags=["assets"])
SessionDependency = Depends(get_session)
_tasks: set[asyncio.Task[None]] = set()


class ImageJobCreate(BaseModel):
    prompt: str = Field(min_length=1, max_length=2000)
    size: str = "1024x1024"


class ImageJob(BaseModel):
    id: str
    status: str
    asset_id: str | None = None
    error: str | None = None


def _asset_path(asset_id: str) -> Path:
    # IDs are generated by us; reject traversal for defensive API use.
    if Path(asset_id).name != asset_id:
        raise HTTPException(400, "Invalid asset id")
    path = assets_directory() / asset_id
    if not path.is_file():
        raise HTTPException(404, "Asset not found")
    return path


def _provider() -> (
    OpenAICompatibleImageProvider | A1111ImageProvider | ComfyUIProvider | StockImageProvider | None
):
    url = settings.image_provider_url
    if settings.image_provider == "openai" and url:
        return OpenAICompatibleImageProvider(
            url, settings.image_provider_api_key, settings.image_provider_model
        )
    if settings.image_provider == "a1111" and url:
        return A1111ImageProvider(url)
    if settings.image_provider == "comfyui" and url:
        return ComfyUIProvider(url)
    if (
        settings.image_provider in {"unsplash", "pexels"}
        and url
        and settings.image_provider_api_key
    ):
        return StockImageProvider(url, settings.image_provider_api_key, settings.image_provider)
    return None


async def _run_image_job(job_id: str, prompt: str, size: str) -> None:
    async with session_factory() as session:
        job = await session.get(ImageJobRecord, job_id)
        if not job:
            return
        try:
            provider = _provider()
            content = await provider.generate(prompt, size) if provider else fallback_image(prompt)
            asset_id = f"{uuid4()}.{image_extension(content)}"
            assets_directory().joinpath(asset_id).write_bytes(content)
            job.status, job.asset_id = "completed", asset_id
        except Exception as exc:
            job.status, job.error = "failed", str(exc)[:2000]
        await session.commit()


def _track(task: asyncio.Task[None]) -> None:
    _tasks.add(task)
    task.add_done_callback(_tasks.discard)


@router.post("/upload", response_model=dict)
async def upload_asset(file: UploadFile = File(...)) -> dict[str, str]:  # noqa: B008
    content = await file.read()
    if len(content) > 20 * 1024 * 1024:
        raise HTTPException(413, "Asset is too large")
    if not content:
        raise HTTPException(400, "Empty asset")
    suffix = Path(file.filename or "").suffix.lower()
    if suffix not in {".png", ".jpg", ".jpeg", ".webp", ".svg"}:
        raise HTTPException(415, "Only image assets are supported")
    asset_id = f"{uuid4()}{suffix}"
    assets_directory().joinpath(asset_id).write_bytes(content)
    return {"asset_id": asset_id, "url": f"/api/assets/{asset_id}"}


@router.get("/{asset_id}")
async def get_asset(asset_id: str) -> FileResponse:
    path = _asset_path(asset_id)
    return FileResponse(path)


@router.post("/jobs", response_model=ImageJob, status_code=202)
async def create_image_job(
    payload: ImageJobCreate, session: AsyncSession = SessionDependency
) -> ImageJob:
    job = ImageJobRecord(id=str(uuid4()), prompt=payload.prompt)
    session.add(job)
    await session.commit()
    _track(asyncio.create_task(_run_image_job(job.id, payload.prompt, payload.size)))
    return ImageJob.model_validate(job, from_attributes=True)


@router.get("/jobs/{job_id}", response_model=ImageJob)
async def get_image_job(job_id: str, session: AsyncSession = SessionDependency) -> ImageJob:
    job = await session.get(ImageJobRecord, job_id)
    if not job:
        raise HTTPException(404, "Image job not found")
    return ImageJob.model_validate(job, from_attributes=True)


@router.post("/jobs/{job_id}/regenerate", response_model=ImageJob, status_code=202)
async def regenerate_image_job(job_id: str, session: AsyncSession = SessionDependency) -> ImageJob:
    job = await session.get(ImageJobRecord, job_id)
    if not job:
        raise HTTPException(404, "Image job not found")
    job.status, job.error, job.asset_id = "queued", None, None
    await session.commit()
    _track(asyncio.create_task(_run_image_job(job.id, job.prompt, "1024x1024")))
    return ImageJob.model_validate(job, from_attributes=True)


@router.get("/jobs/{job_id}/events")
async def image_job_events(
    job_id: str, session: AsyncSession = SessionDependency
) -> StreamingResponse:
    if not await session.get(ImageJobRecord, job_id):
        raise HTTPException(404, "Image job not found")

    async def stream() -> AsyncIterator[str]:
        while True:
            async with session_factory() as current:
                job = await current.get(ImageJobRecord, job_id)
            if not job:
                break
            payload = ImageJob.model_validate(job, from_attributes=True).model_dump()
            yield f"event: status\ndata: {json.dumps(payload)}\n\n"
            if job.status in {"completed", "failed"}:
                break
            await asyncio.sleep(0.15)

    return StreamingResponse(stream(), media_type="text/event-stream")
